/**
 * Unit tests for the Turkish VKN (Vergi Kimlik Numarası) validator.
 * VKN is a 10-digit business tax number with an official checksum.
 * These tests cover valid/invalid checksum cases.
 * Test vectors generated by computing the checksum manually.
 */

import { isValidVKN } from '../vkn';

describe('isValidVKN', () => {
  // --- Valid VKNs (verified by running the checksum algorithm) ---
  it('returns true for a valid VKN: 0010000009', () => {
    expect(isValidVKN('0010000009')).toBe(true);
  });

  it('returns true for another valid VKN: 0010000017', () => {
    expect(isValidVKN('0010000017')).toBe(true);
  });

  it('returns true for valid VKN: 0010000025', () => {
    expect(isValidVKN('0010000025')).toBe(true);
  });

  it('trims surrounding whitespace before validating (valid with spaces)', () => {
    expect(isValidVKN(' 0010000009 ')).toBe(true);
  });

  // --- Invalid VKNs —checksum failures ---
  it('returns false for all zeros', () => {
    expect(isValidVKN('0000000000')).toBe(false);
  });

  it('returns false when checksum digit is wrong (0010000009 → last digit 8)', () => {
    expect(isValidVKN('0010000008')).toBe(false);
  });

  it('returns false when checksum digit is wrong (0010000009 → last digit 1)', () => {
    expect(isValidVKN('0010000001')).toBe(false);
  });

  // --- Format failures ---
  it('returns false for fewer than 10 digits', () => {
    expect(isValidVKN('123456789')).toBe(false);
  });

  it('returns false for more than 10 digits', () => {
    expect(isValidVKN('12345678901')).toBe(false);
  });

  it('returns false for non-digit characters', () => {
    expect(isValidVKN('123456789A')).toBe(false);
  });

  it('returns false for empty string', () => {
    expect(isValidVKN('')).toBe(false);
  });

  it('returns false for a number with dashes', () => {
    expect(isValidVKN('001-000-0009')).toBe(false);
  });

  it('returns false for spaces within the number', () => {
    expect(isValidVKN('0010 000009')).toBe(false);
  });
});
