// AUTO-GENERATED by i18n/sync.mjs — DO NOT EDIT.
// Edit canonical JSON in repo-root i18n/locales/ and re-run the sync.
/* eslint-disable */
import en_activity from './locales/en/activity.json';
import en_admin from './locales/en/admin.json';
import en_auth from './locales/en/auth.json';
import en_business from './locales/en/business.json';
import en_category from './locales/en/category.json';
import en_chrome from './locales/en/chrome.json';
import en_common from './locales/en/common.json';
import en_errors from './locales/en/errors.json';
import en_fact from './locales/en/fact.json';
import en_home from './locales/en/home.json';
import en_panel from './locales/en/panel.json';
import en_profile from './locales/en/profile.json';
import en_review from './locales/en/review.json';
import en_search from './locales/en/search.json';
import en_settings from './locales/en/settings.json';
import en_validation from './locales/en/validation.json';
import tr_activity from './locales/tr/activity.json';
import tr_admin from './locales/tr/admin.json';
import tr_auth from './locales/tr/auth.json';
import tr_business from './locales/tr/business.json';
import tr_category from './locales/tr/category.json';
import tr_chrome from './locales/tr/chrome.json';
import tr_common from './locales/tr/common.json';
import tr_errors from './locales/tr/errors.json';
import tr_fact from './locales/tr/fact.json';
import tr_home from './locales/tr/home.json';
import tr_panel from './locales/tr/panel.json';
import tr_profile from './locales/tr/profile.json';
import tr_review from './locales/tr/review.json';
import tr_search from './locales/tr/search.json';
import tr_settings from './locales/tr/settings.json';
import tr_validation from './locales/tr/validation.json';

export const defaultNS = "common" as const;
export const namespaces = ["activity","admin","auth","business","category","chrome","common","errors","fact","home","panel","profile","review","search","settings","validation"] as const;
export const supportedLocales = ["en","tr"] as const;
export type AppLocale = (typeof supportedLocales)[number];

export const resources = {
  "en": {
    "activity": en_activity,
    "admin": en_admin,
    "auth": en_auth,
    "business": en_business,
    "category": en_category,
    "chrome": en_chrome,
    "common": en_common,
    "errors": en_errors,
    "fact": en_fact,
    "home": en_home,
    "panel": en_panel,
    "profile": en_profile,
    "review": en_review,
    "search": en_search,
    "settings": en_settings,
    "validation": en_validation,
  },
  "tr": {
    "activity": tr_activity,
    "admin": tr_admin,
    "auth": tr_auth,
    "business": tr_business,
    "category": tr_category,
    "chrome": tr_chrome,
    "common": tr_common,
    "errors": tr_errors,
    "fact": tr_fact,
    "home": tr_home,
    "panel": tr_panel,
    "profile": tr_profile,
    "review": tr_review,
    "search": tr_search,
    "settings": tr_settings,
    "validation": tr_validation,
  },
} as const;
