#!/usr/bin/env node
/**
 * i18n sync — single source of truth distributor.
 *
 * Canonical locale JSON lives in `i18n/locales/<locale>/<namespace>.json`.
 * Mobile (Metro) and web (Next) cannot reliably import JSON from outside their
 * own project root, so we COPY the canonical tree into each app and GENERATE a
 * static-import barrel (`resources.generated.ts`) that both bundlers can tree
 * into the graph. Run before dev/build (wired via pre* npm scripts).
 *
 * Usage:
 *   node i18n/sync.mjs            # copy + generate into all apps
 *   node i18n/sync.mjs --check    # verify apps are in sync (CI); exit 1 if not
 *
 * Zero dependencies. Works from any cwd (paths resolved from this file).
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const SRC = join(HERE, 'locales');

// Each app gets the canonical tree copied to <app>/src/i18n/locales plus a
// generated barrel at <app>/src/i18n/resources.generated.ts.
const TARGETS = [
  resolve(ROOT, 'mobile', 'src', 'i18n'),
  resolve(ROOT, 'web', 'src', 'i18n'),
];

const check = process.argv.includes('--check');

const locales = readdirSync(SRC).filter((d) => !d.startsWith('.'));
if (locales.length === 0) {
  console.error('[i18n] no locales found in', SRC);
  process.exit(1);
}

// namespaces = union of json filenames across locales (canonical = first locale)
const nsSet = new Set();
for (const loc of locales) {
  for (const f of readdirSync(join(SRC, loc))) {
    if (f.endsWith('.json')) nsSet.add(f.replace(/\.json$/, ''));
  }
}
const namespaces = [...nsSet].sort();

function buildBarrel() {
  const lines = [
    '// AUTO-GENERATED by i18n/sync.mjs — DO NOT EDIT.',
    '// Edit canonical JSON in repo-root i18n/locales/ and re-run the sync.',
    '/* eslint-disable */',
  ];
  const imports = [];
  const localeEntries = [];
  for (const loc of locales) {
    const nsEntries = [];
    for (const ns of namespaces) {
      const ident = `${loc}_${ns}`.replace(/[^a-zA-Z0-9_]/g, '_');
      const rel = `./locales/${loc}/${ns}.json`;
      if (existsSync(join(SRC, loc, `${ns}.json`))) {
        imports.push(`import ${ident} from '${rel}';`);
        nsEntries.push(`    ${JSON.stringify(ns)}: ${ident},`);
      }
    }
    localeEntries.push(`  ${JSON.stringify(loc)}: {\n${nsEntries.join('\n')}\n  },`);
  }
  lines.push(...imports, '');
  lines.push('export const defaultNS = "common" as const;');
  lines.push(`export const namespaces = ${JSON.stringify(namespaces)} as const;`);
  lines.push(`export const supportedLocales = ${JSON.stringify(locales)} as const;`);
  lines.push('export type AppLocale = (typeof supportedLocales)[number];');
  lines.push('');
  lines.push('export const resources = {');
  lines.push(...localeEntries);
  lines.push('} as const;');
  lines.push('');
  return lines.join('\n');
}

function copyTree(dstLocales) {
  for (const loc of locales) {
    const dstDir = join(dstLocales, loc);
    mkdirSync(dstDir, { recursive: true });
    for (const ns of namespaces) {
      const srcFile = join(SRC, loc, `${ns}.json`);
      if (!existsSync(srcFile)) continue;
      writeFileSync(join(dstDir, `${ns}.json`), readFileSync(srcFile));
    }
  }
}

const barrel = buildBarrel();
let drift = false;

for (const appI18n of TARGETS) {
  const barrelPath = join(appI18n, 'resources.generated.ts');
  const dstLocales = join(appI18n, 'locales');

  if (check) {
    const cur = existsSync(barrelPath) ? readFileSync(barrelPath, 'utf8') : '';
    if (cur !== barrel) {
      console.error('[i18n] OUT OF SYNC:', barrelPath);
      drift = true;
    }
    continue;
  }

  mkdirSync(appI18n, { recursive: true });
  if (existsSync(dstLocales)) rmSync(dstLocales, { recursive: true, force: true });
  copyTree(dstLocales);
  writeFileSync(barrelPath, barrel);
  console.log('[i18n] synced ->', appI18n.replace(ROOT, '.'));
}

if (check && drift) {
  console.error('[i18n] run `node i18n/sync.mjs` and commit the result.');
  process.exit(1);
}
if (check) console.log('[i18n] all apps in sync.');
